### ISSUE TITLE
没有pdf

### ISSUE THREAD

**Issue by minkfusiki** [andy123t/zhbook#1]
为什么用overleaf能正常，但是本地却直接没有pdf呢，用的vscode
![`B~)O6 QFM%LL5)N)IR%R15](https://user-images.githubusercontent.com/104705115/231803565-a9998d19-01de-4bb7-b284-3bc903c4a571.png)
运行结果如图

**Comment by andy123t** [comment]
我的 TeX Live 版本是 texlive2020 没有问题，texlive 2021 应该也没问题，texlive 2022 缺字体
用 TeXPage 平台的几个版本测试过，TeXLive 2021 加 fontset =windows 正常，其他缺字体

主要是 ctex 的字体问题，每个版本都在调整，我也没办法；

另外你可以试试 https://github.com/andy123t/latex-templates 里的模板

**Comment by minkfusiki** [comment]
哦哦，怪不得，我texlive是2023版的，那我去试试能不能调整。
