### ISSUE TITLE
如何插入代码片段

### ISSUE THREAD

**Issue by jackhanyuan** [andy123t/zhbook#2]
你好，非常感谢你的贡献。

我看书中有算法示例，如果需要插入不同语言的代码应该如何使用呢？

**Comment by andy123t** [comment]
你说的应该是插入代码块，实现代码高亮，可以使用 listings 宏包，具体环境可以设置语言类型，比如
```latex
\begin{lstlisting}[language=Python]
Python code
\end{lstlisting}
```
如果你对默认的样式不满意，可以去重新定义样式，参考 [code-latex-style](https://github.com/andy123t/code-latex-style).
